### ISSUE TITLE
Sync only active WHMCS clients

### ISSUE THREAD

**Issue by infinitnet** [goodbytes-gb/Intercom-WHMCS-Module#1]
Hey,

thank you for your work. I didn't try the module yet, but was wondering if it supports syncing only WHMCS clients with Intercom that have a certain status, ie. only active customers for example? And if not, how easy would it be to add this?

Reason is that with old WHMCS databases where 80% or more clients are inactive, syncing all those users would result in well, 80% or more Intercom fees than necessary.

**Comment by mforcer** [comment]
Hi,

It will only sync clients that actually login to WHMCS. Providing 80% if your user base does not log in they will not be synced.

The way this add-on works is: When a client logs in and visits WHMCS admin area, the javascript code collects their name, company, etc and then sends it to Intercom.

If you still want to prevent inactive users from being synced you can either:
1. Disable client details sync so that the inactive user will show up as a regular user in Intercom (with random name).
2. Completely disable the Intercom module for inactive users and therefore would never be created in Intercom.

I will add this feature soon but for now you can simply add the following line of code:

Line 73 above `$output = '`

```
    if (isset($vars['clientsdetails']) && $vars['clientsdetails']['status'] != 'Active') {
        $userData = '' // Prevents non active clients data from being synced.
    }
```

or to completely disable Intercom for non active:

```
    if (isset($vars['clientsdetails']) && $vars['clientsdetails']['status'] != 'Active') {
        return ''; // Completely disable Intercom for non active users.
    }
```

**Comment by infinitnet** [comment]
Wow, that was fast. Thanks!

> It will only sync clients that actually login to WHMCS.

Actually this is good enough for me already. Looks like I misunderstood how the module works then. For some reason I assumed it would loop through tblclients and push every profile to Intercom, but looks like that assumption was wrong.

Your code snippets are going to be useful as well, so thank you for that too!

One last question though: Like you probably know [this](https://cmsbased.net/whmcs-addons/intercom/) is the only competing piece of code. Now they list this as a feature "Toggle security mode so one user can't impersonate another." (no idea how this actually works though). Does your module have a similar feature, so it's actually safe to use Intercom for support requests too and not just generic/sales? Currently trying to decide between the two modules and while I would definitely prefer open source, this and the ability to send custom user attributes (and income of each client to prioritize more valuable clients) to Intercom are the reasons I can't decide what to go with eventually. On the other hand #2 of your roadmap sounds particularly interesting...

**Comment by mforcer** [comment]
@infinitnet I wasn't aware of this paid add-on.. I guess it does something similar.

With this add-on it will be hard to impersonate another user they would need to adjust the javascript on page load and exactly match that user, I'm not quite sure what they are referring to exactly.

I will be adding options to select which custom attributes you may want to use, in the meantime if you want income or anything else I can quickly add it for you.

**Comment by infinitnet** [comment]
Alright, this looks to me like they only try to make the default behaviour of Intercom integration sound more fancy. I'll definitely give your module a shot first - you're extremely responsive. I contacted the developers of that other module at the same time I opened this issue and no response yet.

> I will be adding options to select which custom attributes you may want to use, in the meantime if you want income or anything else I can quickly add it for you.

That's awesome! The income part isn't urgent, I'm only going to evaluate Intercom starting from today - it's just something that would be nice to have in the future (MRC and # of active services maybe rather than total income). So if you could add this to your roadmap, it would be great.

Thank you for your offer though, it's appreciated. Do you have a PayPal ID I can send a donation to?

**Comment by infinitnet** [comment]
Actually this is the "secure mode" they are talking about: https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-secure-mode-on-your-web-product

**Comment by mforcer** [comment]
Thanks for the information.

I wasn't aware of secure mode, it looks quite important, i'm going to spend some time today pushing out an update. I will update in due course.

**Comment by infinitnet** [comment]
Hey, I just wanted to add that I use your module since yesterday and the default behaviour is perfectly fine - there is really no need to mess with what client statuses to sync, as it will only sync active users who also login anyway.

**Comment by mforcer** [comment]
Thanks for the information, Its good to hear you find it useful.

I have started implementing secure mode and attribute choices. An update should be available soon.

**Comment by mforcer** [comment]
It's not quite as easy to grab the income unfortunately as the value in WHMCS is protected meaning it is not intended to be used outside of WHMCS classes. We will need to see if we can construct the query ourselves.

**Comment by mforcer** [comment]
The module now syncs with Income with Intercom.

https://github.com/goodbytes-gb/Intercom-WHMCS-Module/commit/0d103bbf8553f4b4abfa3208745fbeeaaf6e8c14
