### ISSUE TITLE
Sign-up date is off

### ISSUE THREAD

**Issue by infinitnet** [goodbytes-gb/Intercom-WHMCS-Module#2]
Hey, it's me again. After testing this for about 2 days, I noticed that the sign-up dates are completely off in Intercom. It pretty much seems to use the "first seen" date as sign-up date, although that's of course wrong. Your feature list includes syncing of the registration date field to Intercom and it's definitely not doing that.

One other small issue I noticed is that two out of the 20 or so users who signed-in so far have their email address in their name field in Intercom. Both had their actual name in their name field when they signed-in first, but now, a couple of web sessions and hours later, it swapped their name with their email for some reason. Could be some issue with Intercom, but maybe make sure there is no chance your code could feed the email address into their name fields. I'll keep an eye on that and see if other Intercom users get affected by this over time.

Edit: Now a couple of hours after I opened this issue, one of the two user accounts affected by the email in name field issue signed-in to WHMCS and it's showing his name in Intercom again, like it should. So I guess it's not your module afterall but something else causing the name value to get overwritten later on, although the WHMCS module is the only data source / integration I use.. Odd.

**Comment by mforcer** [comment]
Thats odd, we're working on an update will push soon.

Thanks again for the information.

**Comment by infinitnet** [comment]
Hey there, I don't mean to be impatient considering this is an open source project, but do you have any ETA on the push that's going to fix this and the other issues I noticed? Thanks!

**Comment by mforcer** [comment]
HI guys, apologies for the delayed reply. We have been busy launching a new project and after trying out several live chat / lead gen solutions we have decided to move away from Intercom and focus our efforts elsewhere. 

I will leave this repo active incase someone would like to continue developing the app, however moving forward I would recommend CMSBased WHMCS Intercom add-on .. https://cmsbased.net/whmcs-addons/intercom/

Apologies to those of you who have been waiting for an update on this. We may look at it again in the future but too busy at the moment.

**Comment by infinitnet** [comment]
Hey and thanks for the update! I'll move to the CMSBased module then.

Just one question: could you tell me which solution you decided to go with instead? I liked Drift more than Intercom, but decided for the latter because Drift is/was lacking and Android app and there weren't any ready WHMCS integrations.

**Comment by mforcer** [comment]
We also tried Drift but share your concerns and they have decided to double their price from $25 to $50 prompting us to try others in that price point and found GoSquared to offer far greater functionality. They also have a free tier.

It does not offer direct WHMCS integration but we will be modifying this module to work with GoSquared rather than Intercom, which should be up within the next few days.

**Comment by infinitnet** [comment]
I must have missed GoSquared during my research then - first time I hear that name. I'll look into it because our staff also isn't 100% happy with Intercom and it's quite expensive considering it isn't THAT much more than just a common live chat. So thank you again, who knows, maybe we'll follow and move to GoSquared as well.

**Comment by mforcer** [comment]
GoSquared was initially an analytics platform but they have developed it to include chat, lead capture, etc.. it's similar to Intercom. We were also disappointed with the delayed stats provided by Google Analytics so this platform ticks all the boxes as it is mostly in realtime.

I do like Intercom, but their price point will be their downfall. There are much cheaper solutions available.

Good luck with your search.

**Comment by mforcer** [comment]
After working on GoSquared integration i've managed to fix a few problems with this script. I will push an update later today, then at least it's in a better working form.

**Comment by infinitnet** [comment]
Awesome, thanks!

**Comment by mforcer** [comment]
This has been fixed.
